name = "CutCellGeometry"
uuid = "1b180a8f-d98c-4829-a62f-8dd07d08ff73"
authors = ["Fastaxx <Fastaxx@github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
